package resources

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"regexp"
	"strings"
	"terraform-provider-funnel/provider/common"
	"terraform-provider-funnel/provider/funnel"
	"terraform-provider-funnel/provider/planmodifiers"

	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &DataSourceResource{}
var _ resource.ResourceWithImportState = &DataSourceResource{}
var _ resource.ResourceWithConfigValidators = &DataSourceResource{}

func NewDataSourceResource() resource.Resource {
	return &DataSourceResource{}
}

type DataSourceResource struct {
	config *common.FunnelProviderModel
}

type DataSourceResourceModel struct {
	Id               types.String `tfsdk:"id"`
	Workspace        types.String `tfsdk:"workspace"`
	Type             types.String `tfsdk:"type"`
	Name             types.String `tfsdk:"name"`
	DownloadDisabled types.Bool   `tfsdk:"download_disabled"`
	RemoteId         types.String `tfsdk:"remote_id"`
	RemoteStruct     types.String `tfsdk:"remote_struct"`
	ExcludeFromMeld  types.Bool   `tfsdk:"exclude_data_from_funnel"`
	State            types.String `tfsdk:"state"`
	CredentialId     types.String `tfsdk:"credential_id"`
	TemplateId       types.String `tfsdk:"template_id"`
}

type DataSourceJSON struct {
	Key              string          `json:"key"`
	Type             string          `json:"type"`
	Id               string          `json:"id"`
	FunnelAccountId  string          `json:"funnelAccountId"`
	Name             string          `json:"name"`
	ConnectionId     string          `json:"connectionId,omitempty"`
	State            string          `json:"state"`
	ExcludeFromMeld  bool            `json:"excludeFromMeld"`
	DownloadDisabled bool            `json:"downloadDisabled,omitempty"`
	RemoteId         string          `json:"remoteId,omitempty"`
	RemoteStruct     json.RawMessage `json:"remoteStruct,omitempty"`
	TemplateId       string          `json:"templateId,omitempty"`
}

type CreateDataSourceRequest struct {
	FunnelAccountId  string          `json:"funnelAccountId"`
	Type             string          `json:"type"`
	Name             string          `json:"name"`
	ConnectionId     string          `json:"connectionId,omitempty"`
	RemoteId         string          `json:"remoteId,omitempty"`
	RemoteStruct     json.RawMessage `json:"remoteStruct,omitempty"`
	TemplateId       string          `json:"templateId,omitempty"`
	ExcludeFromMeld  bool            `json:"excludeFromMeld,omitempty"`
	DownloadDisabled bool            `json:"downloadDisabled,omitempty"`
}

type UpdateDataSourceRequest struct {
	Name             *string `json:"name,omitempty"`
	FunnelAccountId  *string `json:"funnelAccountId,omitempty"`
	ConnectionId     *string `json:"connectionId,omitempty"`
	ExcludeFromMeld  *bool   `json:"excludeFromMeld,omitempty"`
	DownloadDisabled *bool   `json:"downloadDisabled,omitempty"`
}

func (r *DataSourceResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_data_source"
}

func (r *DataSourceResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Manages a Funnel data source, which represents a connection to an advertising platform or analytics system. Data sources pull data from external platforms into Funnel for aggregation and analysis.",
		Attributes: map[string]schema.Attribute{
			"workspace": schema.StringAttribute{
				MarkdownDescription: "The Funnel workspace ID where this data source will be created. Must be exactly 20 characters.",
				Required:            true,
				Validators: []validator.String{
					stringvalidator.RegexMatches(
						regexp.MustCompile(`^[A-Za-z0-9-_]{20}$`),
						"must be exactly 20 characters and contain only alphanumeric characters, hyphens, and underscores",
					),
				},
			},
			"id": schema.StringAttribute{
				MarkdownDescription: "The unique identifier (key) for this data source in Funnel. This value is generated by Funnel and used for API operations.",
				Computed:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"type": schema.StringAttribute{
				MarkdownDescription: "The source type identifier. Supported values include: `adwords` (Google Ads), `facebookads` (Facebook Ads), `tiktok` (TikTok Ads), `bing` (Microsoft Ads), `spotifyads` (Spotify Ads), `linkedin_api` (LinkedIn Ads), `instagraminsights` (Instagram Insights), `reddit` (Reddit Ads). Changing this forces a new resource to be created.",
				Required:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
				Validators: []validator.String{
					stringvalidator.RegexMatches(
						regexp.MustCompile(`^[A-Za-z0-9_-]{1,127}$`),
						"must be 1-127 characters and contain only alphanumeric characters, underscores, and hyphens",
					),
				},
			},
			"name": schema.StringAttribute{
				MarkdownDescription: "The display name for this data source as it will appear in the Funnel interface. Should be descriptive and help identify the account or configuration (e.g., \"Google Ads - Main Account\").",
				Required:            true,
				Validators: []validator.String{
					stringvalidator.LengthBetween(1, 255),
				},
			},
			"download_disabled": schema.BoolAttribute{
				MarkdownDescription: "When set to `true`, prevents Funnel from downloading data from this data source. Useful for temporarily pausing data collection without deleting the data source configuration. Defaults to `false`.",
				Optional:            true,
				Computed:            true,
			},
			"remote_id": schema.StringAttribute{
				MarkdownDescription: "The identifier of the account or entity in the source system (e.g., Google Ads customer ID, Facebook Ads account ID). Required for most advertising platforms. Changing this forces a new resource to be created.",
				Optional:            true,
				Computed:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
				Validators: []validator.String{
					stringvalidator.LengthAtLeast(1),
				},
			},
			"exclude_data_from_funnel": schema.BoolAttribute{
				MarkdownDescription: "When set to `true`, excludes data from this source from being included in Funnel aggregations and queries. The data source will still download and store data, but it won't be available for analysis. Could be useful if you want to validate the data before it is used in Funnel. Defaults to `false`.",
				Optional:            true,
				Computed:            true,
			},
			"state": schema.StringAttribute{
				MarkdownDescription: "The current operational state of the data source in Funnel (e.g., `OK`, `UNAUTHORIZED`, `INVALID`, `DISABLED`). This is managed by Funnel and reflects the health and status of the data source connection.",
				Computed:            true,
			},
			"credential_id": schema.StringAttribute{
				MarkdownDescription: "The ID of the credential used to authenticate with the external platform. This references a credential that must have already been created in Funnel. The credential musst have been shared with the System user in Funnel before it can be used here.",
				Optional:            true,
				Computed:            true,
			},
			"template_id": schema.StringAttribute{
				MarkdownDescription: "The template ID that defines what data to collect. Built-in templates use the format `funnel:<hash>` (e.g., `funnel:a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4`). Custom templates use the format `<prefix>-<hash>` (e.g., `tiktok-a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4`). Changing this forces a new resource to be created.",
				Optional:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
				Validators: []validator.String{
					stringvalidator.RegexMatches(
						regexp.MustCompile(`^(funnel:|[A-Za-z0-9_-]{1,127}-)[a-z0-9]{32}$`),
						"must be a valid template ID: 'funnel:<32-char-hash>' for built-in or '<prefix>-<32-char-hash>' for custom templates",
					),
				},
			},
			"remote_struct": schema.StringAttribute{
				MarkdownDescription: "A JSON-encoded object containing remote identity fields for connectors that require multiple account identifiers (e.g., `jsonencode({customer_id = \"123\", login_customer_id = \"456\"})` for Google Ads). Mutually exclusive with `remote_id`. Changing this forces a new resource to be created.",
				Optional:            true,
				Computed:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
					planmodifiers.JSONSemanticEqual(),
				},
				Validators: []validator.String{
					stringvalidator.LengthAtLeast(2),
				},
			},
		},
	}
}

func (r *DataSourceResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	config, ok := req.ProviderData.(*common.FunnelProviderModel)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *FunnelProviderModel, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)
		return
	}
	r.config = config
}

func (r *DataSourceResource) ConfigValidators(ctx context.Context) []resource.ConfigValidator {
	return []resource.ConfigValidator{
		&remoteFieldsExclusivityValidator{},
	}
}

type remoteFieldsExclusivityValidator struct{}

func (v *remoteFieldsExclusivityValidator) Description(ctx context.Context) string {
	return "Validates that remote_id and remote_struct are not both specified."
}

func (v *remoteFieldsExclusivityValidator) MarkdownDescription(ctx context.Context) string {
	return "Validates that `remote_id` and `remote_struct` are not both specified."
}

func (v *remoteFieldsExclusivityValidator) ValidateResource(ctx context.Context, req resource.ValidateConfigRequest, resp *resource.ValidateConfigResponse) {
	var remoteId types.String
	var remoteStruct types.String

	resp.Diagnostics.Append(req.Config.GetAttribute(ctx, path.Root("remote_id"), &remoteId)...)
	resp.Diagnostics.Append(req.Config.GetAttribute(ctx, path.Root("remote_struct"), &remoteStruct)...)

	if resp.Diagnostics.HasError() {
		return
	}

	if !remoteId.IsNull() && !remoteId.IsUnknown() && !remoteStruct.IsNull() && !remoteStruct.IsUnknown() {
		resp.Diagnostics.AddAttributeError(
			path.Root("remote_struct"),
			"Conflicting Remote Identity Fields",
			"Only one of remote_id or remote_struct may be specified. Use remote_id for connectors with a single account identifier, or remote_struct for connectors requiring multiple identifiers.",
		)
	}
}

func (r *DataSourceResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data DataSourceResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	payload := CreateDataSourceRequest{
		FunnelAccountId: data.Workspace.ValueString(),
		Type:            data.Type.ValueString(),
		Name:            data.Name.ValueString(),
	}

	// Add optional fields if provided
	if !data.CredentialId.IsNull() && !data.CredentialId.IsUnknown() {
		payload.ConnectionId = data.CredentialId.ValueString()
	}
	if !data.ExcludeFromMeld.IsNull() && !data.ExcludeFromMeld.IsUnknown() {
		payload.ExcludeFromMeld = data.ExcludeFromMeld.ValueBool()
	}
	if !data.DownloadDisabled.IsNull() && !data.DownloadDisabled.IsUnknown() {
		payload.DownloadDisabled = data.DownloadDisabled.ValueBool()
	}
	if !data.RemoteId.IsNull() && !data.RemoteId.IsUnknown() {
		payload.RemoteId = data.RemoteId.ValueString()
	}
	if !data.RemoteStruct.IsNull() && !data.RemoteStruct.IsUnknown() {
		payload.RemoteStruct = json.RawMessage(data.RemoteStruct.ValueString())
	}
	if !data.TemplateId.IsNull() && !data.TemplateId.IsUnknown() {
		payload.TemplateId = data.TemplateId.ValueString()
	}

	respObj, err := funnel.CreateWorkspaceEntity[CreateDataSourceRequest, DataSourceJSON](ctx, "datasources", r.config, data.Workspace.ValueString(), payload)
	if err != nil {
		if err.StatusCode == 409 {
			resp.Diagnostics.AddError(
				"Data source already exists",
				fmt.Sprintf("A data source with the same configuration already exists: %v", err.Details),
			)
			return
		}
		resp.Diagnostics.AddError(
			"Error Creating Data Source",
			"Could not create data source: "+err.Error(),
		)
		return
	}

	data.Id = types.StringValue(respObj.Key)
	data.Workspace = types.StringValue(respObj.FunnelAccountId)
	data.Type = types.StringValue(respObj.Type)
	data.Name = types.StringValue(respObj.Name)
	data.DownloadDisabled = types.BoolValue(respObj.DownloadDisabled)
	data.ExcludeFromMeld = types.BoolValue(respObj.ExcludeFromMeld)
	data.State = types.StringValue(respObj.State)

	if respObj.ConnectionId != "" {
		data.CredentialId = types.StringValue(respObj.ConnectionId)
	} else {
		data.CredentialId = types.StringNull()
	}

	if respObj.RemoteId != "" {
		data.RemoteId = types.StringValue(respObj.RemoteId)
	} else {
		data.RemoteId = types.StringNull()
	}

	if len(respObj.RemoteStruct) > 0 && string(respObj.RemoteStruct) != "null" {
		data.RemoteStruct = types.StringValue(string(respObj.RemoteStruct))
	} else {
		data.RemoteStruct = types.StringNull()
	}

	if respObj.TemplateId != "" {
		data.TemplateId = types.StringValue(respObj.TemplateId)
	} else {
		data.TemplateId = types.StringNull()
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *DataSourceResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data DataSourceResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	ds, err := funnel.GetWorkspaceEntity[DataSourceJSON](ctx, "datasources", r.config, data.Workspace.ValueString(), data.Id.ValueString())
	if err != nil {
		var apiErr funnel.APIError
		if errors.As(err, &apiErr) && apiErr.StatusCode == 404 {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError(
			"Error Reading Data Source",
			"Could not read data source ID "+data.Id.ValueString()+": "+err.Error(),
		)
		return
	}

	data.Workspace = types.StringValue(ds.FunnelAccountId)
	data.Type = types.StringValue(ds.Type)
	data.Name = types.StringValue(ds.Name)
	data.DownloadDisabled = types.BoolValue(ds.DownloadDisabled)
	data.ExcludeFromMeld = types.BoolValue(ds.ExcludeFromMeld)
	data.State = types.StringValue(ds.State)

	if ds.ConnectionId != "" {
		data.CredentialId = types.StringValue(ds.ConnectionId)
	} else {
		data.CredentialId = types.StringNull()
	}

	if ds.RemoteId != "" {
		data.RemoteId = types.StringValue(ds.RemoteId)
	} else {
		data.RemoteId = types.StringNull()
	}

	if len(ds.RemoteStruct) > 0 && string(ds.RemoteStruct) != "null" {
		data.RemoteStruct = types.StringValue(string(ds.RemoteStruct))
	} else {
		data.RemoteStruct = types.StringNull()
	}

	if ds.TemplateId != "" {
		data.TemplateId = types.StringValue(ds.TemplateId)
	} else {
		data.TemplateId = types.StringNull()
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *DataSourceResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var data DataSourceResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	payload := UpdateDataSourceRequest{}

	// Only include fields that are being updated
	if !data.Name.IsNull() && !data.Name.IsUnknown() {
		name := data.Name.ValueString()
		payload.Name = &name
	}

	if !data.CredentialId.IsNull() && !data.CredentialId.IsUnknown() {
		credentialId := data.CredentialId.ValueString()
		payload.ConnectionId = &credentialId
	}

	if !data.ExcludeFromMeld.IsNull() && !data.ExcludeFromMeld.IsUnknown() {
		excludeFromMeld := data.ExcludeFromMeld.ValueBool()
		payload.ExcludeFromMeld = &excludeFromMeld
	}

	if !data.DownloadDisabled.IsNull() && !data.DownloadDisabled.IsUnknown() {
		downloadDisabled := data.DownloadDisabled.ValueBool()
		payload.DownloadDisabled = &downloadDisabled
	}

	respObj, err := funnel.PatchWorkspaceEntity[UpdateDataSourceRequest, DataSourceJSON](ctx, "datasources", r.config, data.Workspace.ValueString(), data.Id.ValueString(), payload)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error Updating Data Source",
			"Could not update data source ID "+data.Id.ValueString()+": "+err.Error(),
		)
		return
	}

	data.Workspace = types.StringValue(respObj.FunnelAccountId)
	data.Type = types.StringValue(respObj.Type)
	data.Name = types.StringValue(respObj.Name)
	data.DownloadDisabled = types.BoolValue(respObj.DownloadDisabled)
	data.ExcludeFromMeld = types.BoolValue(respObj.ExcludeFromMeld)
	data.State = types.StringValue(respObj.State)

	if respObj.ConnectionId != "" {
		data.CredentialId = types.StringValue(respObj.ConnectionId)
	} else {
		data.CredentialId = types.StringNull()
	}

	if respObj.RemoteId != "" {
		data.RemoteId = types.StringValue(respObj.RemoteId)
	} else {
		data.RemoteId = types.StringNull()
	}

	if len(respObj.RemoteStruct) > 0 && string(respObj.RemoteStruct) != "null" {
		data.RemoteStruct = types.StringValue(string(respObj.RemoteStruct))
	} else {
		data.RemoteStruct = types.StringNull()
	}

	if respObj.TemplateId != "" {
		data.TemplateId = types.StringValue(respObj.TemplateId)
	} else {
		data.TemplateId = types.StringNull()
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *DataSourceResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data DataSourceResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	tflog.Info(ctx, "Deleting data source", map[string]any{
		"id":        data.Id.ValueString(),
		"workspace": data.Workspace.ValueString(),
	})

	err := funnel.DeleteWorkspaceEntity(ctx, "datasources", r.config, data.Workspace.ValueString(), data.Id.ValueString())
	if err != nil {
		resp.Diagnostics.AddError(
			"Error Deleting Data Source",
			"Could not delete data source ID "+data.Id.ValueString()+": "+err.Error(),
		)
	}
}

func (r *DataSourceResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	idParts := strings.Split(req.ID, "/")
	if len(idParts) != 2 {
		resp.Diagnostics.AddError(
			"Invalid Import ID",
			"Expected import ID in format 'workspace_id/data_source_id', got: "+req.ID,
		)
		return
	}

	workspaceID := idParts[0]
	dataSourceID := idParts[1]

	ds, err := funnel.GetWorkspaceEntity[DataSourceJSON](ctx, "datasources", r.config, workspaceID, dataSourceID)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error Importing Data Source",
			"Could not read data source ID "+dataSourceID+" from workspace "+workspaceID+": "+err.Error(),
		)
		return
	}

	var credentialId types.String
	if ds.ConnectionId != "" {
		credentialId = types.StringValue(ds.ConnectionId)
	} else {
		credentialId = types.StringNull()
	}

	var remoteId types.String
	if ds.RemoteId != "" {
		remoteId = types.StringValue(ds.RemoteId)
	} else {
		remoteId = types.StringNull()
	}

	var remoteStruct types.String
	if len(ds.RemoteStruct) > 0 && string(ds.RemoteStruct) != "null" {
		remoteStruct = types.StringValue(string(ds.RemoteStruct))
	} else {
		remoteStruct = types.StringNull()
	}

	var templateId types.String
	if ds.TemplateId != "" {
		templateId = types.StringValue(ds.TemplateId)
	} else {
		templateId = types.StringNull()
	}

	data := DataSourceResourceModel{
		Id:               types.StringValue(dataSourceID),
		Workspace:        types.StringValue(ds.FunnelAccountId),
		Type:             types.StringValue(ds.Type),
		Name:             types.StringValue(ds.Name),
		DownloadDisabled: types.BoolValue(ds.DownloadDisabled),
		ExcludeFromMeld:  types.BoolValue(ds.ExcludeFromMeld),
		State:            types.StringValue(ds.State),
		CredentialId:     credentialId,
		RemoteId:         remoteId,
		RemoteStruct:     remoteStruct,
		TemplateId:       templateId,
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
